<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php include('inc/header.php'); ?>
</head>

<body>
<?php include('inc/topo.php'); ?>
<div id="main">
<div id="main-left">
	
    
    
    <div class="contorno-meio">
    <h2> Termos de uso:</h2>
	<p>Este documento (Termo de Uso) apresenta os termos e condi&ccedil;&otilde;es aplic&aacute;veisao uso dos servi&ccedil;os oferecidos por Pernambuco Tecnologia Digitais LTDA,&nbsp;doravante denominada "&Eacute; de gra&ccedil;a", disponibilizados no sitewww.edegraca.com.br (Servi&ccedil;os).AO UTILIZAR OS SERVI&Ccedil;OS, INDEPENDENTE DO MOMENTO DE SEU CADASTRO, OUSU&Aacute;RIO ("USU&Aacute;RIO"): (1) CONFIRMA QUE LEU E COMPREENDEU OS TERMOS ECONDI&Ccedil;&Otilde;ES ESTABELECIDOS NOS TERMOS DE USO, ASSIM COMO NOS DEMAISDOCUMENTOS APRESENTADOS NO SITE WWW.EDEGRACA.COM.BR; E QUE (2) ACEITAR&Aacute;AUTOMATICAMENTE ESTES TERMOS DE USO, BEM COMO TODOS OS DEMAIS TERMOS,CONDI&Ccedil;&Otilde;ES E INFORMA&Ccedil;&Otilde;ES CONSTANTES DO WEBSITE WWW.EDEGRACA.COM.BR E N&Atilde;ONECESSARIAMENTE DESCRITOS NESTES TERMOS DE USO.</p>
<p>&nbsp;</p>
<p>1. OBJETO.</p>
<p>1.1 O &Eacute; de gra&ccedil;a presta um servi&ccedil;o interativo de intermedia&ccedil;&atilde;o de servi&ccedil;os e/ou produtos de terceiros, por meio da publica&ccedil;&atilde;o de ofertas e promo&ccedil;&otilde;es (&ldquo;OFERTA&rdquo;) no Site, a serem adquiridas, observadas certas condi&ccedil;&otilde;es, por meio da compra de cupons (&ldquo;Cupons&rdquo;). Tais servi&ccedil;os s&atilde;o operados e administrados pelo &Eacute; de gra&ccedil;a na rede mundial de computadores (&ldquo;Internet&rdquo;).</p>
<p>1.2 A possibilidade de aquisi&ccedil;&atilde;o com desconto dos produtos e/ou servi&ccedil;os das empresas parceiras ("Parceiro") ocorre a partir da pr&eacute; negocia&ccedil;&atilde;o entre o &Eacute; de gra&ccedil;a e o Parceiro de um n&uacute;mero m&iacute;nimo de aquisi&ccedil;&otilde;es de determinado produto e/ou servi&ccedil;o que devem acontecer atrav&eacute;s do website.</p>
<p>1.3 Uma vez atingido e/ou ultrapassado o n&uacute;mero m&iacute;nimo de aquisi&ccedil;&otilde;es previamente estabelecido a Oferta ser&aacute; validada e o Usu&aacute;rio receber&aacute; os produtos e/ou servi&ccedil;os adquiridos diretamente do Parceiro atrav&eacute;s da apresenta&ccedil;&atilde;o de um cupom eletr&ocirc;nico distribu&iacute;do pelo &Eacute; de gra&ccedil;a aos compradores.</p>
<p>1.4 A publica&ccedil;&atilde;o, aquisi&ccedil;&atilde;o e entrega da Oferta acontecer&aacute; conforme as seguintes etapas:</p>
<p>a) Publica&ccedil;&atilde;o da Oferta: A Oferta ser&aacute; publicada no website do &Eacute; de gra&ccedil;a e assim permanecer&aacute; durante o per&iacute;odo de horas indicado no pr&oacute;prio website ou enquanto n&atilde;o atingir a quantidade m&aacute;xima de cupons quando especificado nas condi&ccedil;&otilde;es ("Per&iacute;odo de Publica&ccedil;&atilde;o") para conhecimento pelos Usu&aacute;rios do n&uacute;mero m&iacute;nimo de aquisi&ccedil;&otilde;es esperadas para valida&ccedil;&atilde;o da Oferta, conhecimento das espec&iacute;ficas condi&ccedil;&otilde;es de utiliza&ccedil;&atilde;o e/ou entrega do produto e aquisi&ccedil;&atilde;o da Oferta por parte dos Usu&aacute;rios.</p>
<p>b) Aquisi&ccedil;&atilde;o da Oferta: O Usu&aacute;rio interessado em adquirir a Oferta, exclusivamente durante o Per&iacute;odo de Publica&ccedil;&atilde;o, dever&aacute; manifestar-se eletronicamente atrav&eacute;s do website, efetuando o pagamento conforme instru&ccedil;&otilde;es indicadas no pr&oacute;prio website. O n&uacute;mero m&iacute;nimo de aquisi&ccedil;&otilde;es pr&eacute;-estabelecido para a valida&ccedil;&atilde;o de cada Oferta ser&aacute; contabilizado atrav&eacute;s do n&uacute;mero de aquisi&ccedil;&otilde;es efetuadas atrav&eacute;s do website. O website informar&aacute; durante todo Per&iacute;odo de Publica&ccedil;&atilde;o o n&uacute;mero de aquisi&ccedil;&otilde;es j&aacute; efetuadas.</p>
<p>c) Valida&ccedil;&atilde;o da Oferta: A Oferta publicada no website do &Eacute; de gra&ccedil;a ser&aacute; validada automaticamente apenas quando o n&uacute;mero de aquisi&ccedil;&otilde;es efetuadas atrav&eacute;s do website for igual ao n&uacute;mero m&iacute;nimo de aquisi&ccedil;&otilde;es estabelecido especificamente para cada Oferta de produto e/ou servi&ccedil;o. Caso a Oferta n&atilde;o seja validada, as aquisi&ccedil;&otilde;es efetuadas ficam automaticamente canceladas e os Usu&aacute;rios n&atilde;o ter&atilde;o seu cart&atilde;o de cr&eacute;dito debitado. Caso a oferta seja validada o &Eacute; de gra&ccedil;a poder&aacute; debitar o valor de compra do Cupom diretamente do Usu&aacute;rio, sem necessidade de qualquer autoriza&ccedil;&atilde;o adicional ou aviso pr&eacute;vio.</p>
<p>d) Entrega dos Produtos e/ou Servi&ccedil;os Ofertados: Ap&oacute;s a Valida&ccedil;&atilde;o da Oferta, o &Eacute;de gra&ccedil;a ir&aacute; confirmar a Aquisi&ccedil;&atilde;o da Oferta aos Usu&aacute;rios que realizaram a compra e distribuir&aacute; eletronicamente um c&oacute;digo num&eacute;rico para identifica&ccedil;&atilde;o, juntamente com todas as condi&ccedil;&otilde;es de uso e/ou entrega inicialmente publicadas no website, para que os produtos e/ou servi&ccedil;os sejam recebidos do Parceiro.</p>
<p>&nbsp;</p>
<p>2 CADASTRO</p>
<p>2.1 O &Eacute; de gra&ccedil;a, neste ato, concede ao Usu&aacute;rio uma licen&ccedil;a pessoal limitada, n&atilde;o exclusiva, n&atilde;o transfer&iacute;vel, revog&aacute;vel, por prazo indeterminado, consoante este Contrato, para utilizar o Site, a fim de avaliar, manifestar o interesse em adquirir e eventualmente adquirir as Promo&ccedil;&otilde;es. O direito de utiliza&ccedil;&atilde;o do Site &eacute; pessoal e intransfer&iacute;vel. Para fins de cadastramento, o Usu&aacute;rio forneceu &agrave; &Eacute; de gra&ccedil;a as informa&ccedil;&otilde;es necess&aacute;rias ao seu cadastramento e criou um nome (login) e uma senha. O Usu&aacute;rio declara e reconhece que as informa&ccedil;&otilde;es sobre si fornecidas s&atilde;o verdadeiras, corretas, atuais e completas, responsabilizando-se civil e criminalmente por essas informa&ccedil;&otilde;es. Caso os dados informados pelo Usu&aacute;rio no momento do cadastramento estejam errados ou incompletos, impossibilitando a comprova&ccedil;&atilde;o e identifica&ccedil;&atilde;o do Usu&aacute;rio, o &Eacute; de gra&ccedil;a ter&aacute; o direito de suspender imediatamente a presta&ccedil;&atilde;o de servi&ccedil;os prestados por meio do Site, sem necessidade de pr&eacute;vio aviso, e haver do Usu&aacute;rio as perdas e danos eventualmente sofridos.</p>
<p>2.2 O Usu&aacute;rio &eacute; respons&aacute;vel pela prote&ccedil;&atilde;o da confidencialidade de sua senha pessoal. O Usu&aacute;rio autoriza expressamente o &Eacute; de gra&ccedil;a a manter em seu cadastro as informa&ccedil;&otilde;es fornecidas pelo Usu&aacute;rio, bem como autoriza o &Eacute; de gra&ccedil;a a fornecer as informa&ccedil;&otilde;es constantes de referido cadastro a autoridades p&uacute;blicas que as solicitarem conforme permitido pela legisla&ccedil;&atilde;o em vigor e a seus parceiros estrat&eacute;gicos, comerciais ou t&eacute;cnicos, com a finalidade de oferecer melhores condi&ccedil;&otilde;es de Promo&ccedil;&otilde;es e/ou conte&uacute;dos ao Usu&aacute;rio. Ademais, o Usu&aacute;rio permite expressamente &agrave; &Eacute; de gra&ccedil;a coletar informa&ccedil;&otilde;es para realiza&ccedil;&atilde;o de acompanhamento de tr&aacute;fego, com intuito de identificar grupos e perfis de usu&aacute;rios, bem assim para fins de orienta&ccedil;&atilde;o publicit&aacute;ria.</p>
<p>2.3 O Usu&aacute;rio se compromete a comunicar &agrave; &Eacute; de gra&ccedil;a por meio do servi&ccedil;o de atendimento ao cliente (&ldquo;SAC&rdquo;), o extravio, perda, furto ou roubo das senhas de acesso imediatamente ap&oacute;s o conhecimento do fato. At&eacute; o momento em que efetivamente comunicar &agrave; &Eacute; de gra&ccedil;a o extravio, perda, furto ou roubo de senha de acesso, o Usu&aacute;rio ser&aacute; o &uacute;nico respons&aacute;vel pelos gastos e/ou preju&iacute;zos decorrentes da sua eventual utiliza&ccedil;&atilde;o por terceiros, n&atilde;o tendo o &Eacute; de gra&ccedil;a qualquer responsabilidade por eventuais danos decorrentes de tais fatos.</p>
<p>2.4 Os servi&ccedil;os do &Eacute; de gra&ccedil;a est&atilde;o dispon&iacute;veis apenas para as pessoas que tenham capacidade legal para contrat&aacute;-los. N&atilde;o podem utiliz&aacute;-los, assim, pessoas que n&atilde;o gozem dessa capacidade, inclusive menores de idade, ou pessoas que tenham sido inabilitadas do &Eacute; de gra&ccedil;a tempor&aacute;ria ou definitivamente.</p>
<p>&nbsp;</p>
<p>3 PRIVACIDADE DA INFORMA&Ccedil;&Atilde;O.</p>
<p>3.1 O &Eacute; de gra&ccedil;a tomar&aacute; todas as medidas poss&iacute;veis para manter a confidencialidade e a seguran&ccedil;a descritas nesta cl&aacute;usula, por&eacute;m n&atilde;o responder&aacute; por preju&iacute;zo que possa ser derivado da viola&ccedil;&atilde;o dessas medidas por parte de terceiros que utilizem as redes p&uacute;blicas ou a internet, subvertendo os sistemas de seguran&ccedil;a para acessar as informa&ccedil;&otilde;es de Usu&aacute;rios.</p>
<p>3.2 O Usu&aacute;rio expressamente aceita que o &Eacute; de gra&ccedil;a e/ou qualquer de seus parceiros enviem ao Usu&aacute;rio mensagens de e-mail ou de SMS de car&aacute;ter informativo, referentes a comunica&ccedil;&otilde;es espec&iacute;ficas referentes a Promo&ccedil;&otilde;es disponibilizadas ou que venham a ser disponibilizadas no Site, bem como outras mensagens de natureza comercial, tais como ofertas dos terceiros licenciantes do &Eacute; de gra&ccedil;a e novidades do Site. Caso o Usu&aacute;rio n&atilde;o deseje mais receber referidas mensagens dever&aacute; solicitar o cancelamento do seu envio no pr&oacute;prio Site.</p>
<p>&nbsp;</p>
<p>4 OBRIGA&Ccedil;&Otilde;ES DOS USU&Aacute;RIOS.</p>
<p>4.1 Os Usu&aacute;rios interessados nas Ofertas anunciadas pelo &Eacute; de gra&ccedil;a devem realizar as aquisi&ccedil;&otilde;es e pagamento durante o Per&iacute;odo de Publica&ccedil;&atilde;o. A Publica&ccedil;&atilde;o da Oferta encerra-se quando expirado o prazo supra definido pelo &Eacute; de gra&ccedil;a ou quando esgotar a quantidade do produto e/ou servi&ccedil;o oferecido pelo Parceiro sem aviso pr&eacute;vio.</p>
<p>4.2 O Usu&aacute;rio adquirente, ap&oacute;s manifestar-se pela Aquisi&ccedil;&atilde;o da Oferta, obriga-se a adquirir a Oferta no caso de sua Valida&ccedil;&atilde;o, bem como a seu pagamento. A Oferta de Compra &eacute; irrevog&aacute;vel, nos termos dos artigos 427 e 429 do C&oacute;digo Civil, ressalvadas circunst&acirc;ncias excepcionais.</p>
<p>4.3 Ao adquirir a Oferta atrav&eacute;s do website o Usu&aacute;rio comprador declara-se ciente sobre as condi&ccedil;&otilde;es de recebimento e/ou uso do produto e/ou servi&ccedil;o publicadas no website e reproduzidas no cupom eletr&ocirc;nico.</p>
<p>4.4 O &Eacute; de gra&ccedil;a n&atilde;o se responsabiliza pelas obriga&ccedil;&otilde;es tribut&aacute;rias que recaiam sobre as atividades dos Usu&aacute;rios do site, bem como sobre a de seus Parceiros. Assim como estabelece a legisla&ccedil;&atilde;o pertinente em vigor, o consumidor dever&aacute; exigir nota fiscal do Parceiro em suas transa&ccedil;&otilde;es.</p>
<p>&nbsp;</p>
<p>5. RESPONSABILIDADES.</p>
<p>5.1. Em nenhuma circunst&acirc;ncia o &Eacute; de gra&ccedil;ao ser&aacute; respons&aacute;vel pela qualidade, pontualidade ou exatid&atilde;o dos servi&ccedil;os prestados e/ou dos produtos ofertados por seus fornecedores, terceiros licenciantes e demais parceiros anunciados no site.</p>
<p>5.2 O &Eacute; de gra&ccedil;a n&atilde;o &eacute; o propriet&aacute;rio dos produtos e/ou servi&ccedil;os ofertados pelos Parceiros, n&atilde;o guarda a posse deles e n&atilde;o realiza Ofertas em seu nome. Tampouco interv&eacute;m na entrega e/ou uso dos produtos e/ou servi&ccedil;os cuja aquisi&ccedil;&atilde;o ocorra atrav&eacute;s do website.</p>
<p>5.3 O &Eacute; de gra&ccedil;a n&atilde;o se responsabiliza pela capacidade para contratar dos Usu&aacute;rios ou pela veracidade dos dados pessoais por eles inseridos em seus cadastros. n&atilde;o outorga garantia por v&iacute;cios ocultos ou aparentes nas negocia&ccedil;&otilde;es entre os Usu&aacute;rios.</p>
<p>5.4 O &Eacute; de gra&ccedil;a n&atilde;o ser&aacute; respons&aacute;vel pelo efetivo cumprimento das obriga&ccedil;&otilde;es assumidas pelos Usu&aacute;rios. O Usu&aacute;rio reconhece e aceita que ao adquirir produtos e/ou servi&ccedil;os dos Parceiros o faz por sua conta e risco. Em nenhum caso o &Eacute; de gra&ccedil;a ser&aacute; respons&aacute;vel pelo lucro cessante ou por qualquer outro dano e/ou preju&iacute;zo que o Usu&aacute;rio possa sofrer devido &agrave;s aquisi&ccedil;&otilde;es realizadas atrav&eacute;s do website</p>
<p>5.5 O &Eacute; de gra&ccedil;a n&atilde;o se responsabiliza pela perda, roubo, danifica&ccedil;&atilde;o ou extravio do cupom numerado para identifica&ccedil;&atilde;o da Aquisi&ccedil;&atilde;o da Oferta, ap&oacute;s a realiza&ccedil;&atilde;o da distribui&ccedil;&atilde;o eletr&ocirc;nica ao Usu&aacute;rio. O n&uacute;mero inscrito no cupom ser&aacute; o elemento identificador da Aquisi&ccedil;&atilde;o da Oferta perante o Parceiro sendo a manuten&ccedil;&atilde;o de sua seguran&ccedil;a, e sua divulga&ccedil;&atilde;o a terceiros, de exclusiva responsabilidade do Usu&aacute;rio adquirente.</p>
<p>5.6 O Usu&aacute;rio concorda que:</p>
<p>a) As exclus&otilde;es de garantia e limita&ccedil;&otilde;es de responsabilidade estabelecidas acima s&atilde;o elementos fundamentais da base do contrato ora celebrado com o &Eacute; de gra&ccedil;a.</p>
<p>b) O &Eacute; de gra&ccedil;a n&atilde;o poderia prestar os servi&ccedil;os e/ou fornecer os produtos dispon&iacute;veis no Site em uma base economicamente razo&aacute;vel sem essas limita&ccedil;&otilde;es.</p>
<p>c) As exclus&otilde;es de garantia e limita&ccedil;&otilde;es de responsabilidade refletem uma aloca&ccedil;&atilde;o razo&aacute;vel e justa de riscos entre o Usu&aacute;rio e o &Eacute; de gra&ccedil;a. A exclus&atilde;o de garantia e as limita&ccedil;&otilde;es de responsabilidades acima s&atilde;o estendidas para o benef&iacute;cio de todos os terceiros licenciantes do &Eacute; de gra&ccedil;a.</p>
<p>&nbsp;</p>
<p>6 PROPRIEDADE INTELECTUAL.</p>
<p>6.1 Todo o conte&uacute;do dispon&iacute;vel no Site, incluindo os Microsites, &eacute; de propriedade exclusiva do &Eacute; de gra&ccedil;a e de seus terceiros licenciantes. &Eacute; proibida a c&oacute;pia, distribui&ccedil;&atilde;o, transmiss&atilde;o, publica&ccedil;&atilde;o, conex&atilde;o ou qualquer outro tipo de modifica&ccedil;&atilde;o do Site ou dos Microsites sem expressa autoriza&ccedil;&atilde;o do &Eacute; de gra&ccedil;a.</p>
<p>6.2 Qualquer viola&ccedil;&atilde;o do disposto nesta cl&aacute;usula constituir&aacute; infra&ccedil;&atilde;o de direitos de propriedade intelectual e sujeitar&aacute; o Usu&aacute;rio &agrave;s san&ccedil;&otilde;es administrativas, civis e criminais aplic&aacute;veis.</p>
<p>6.3 O &Eacute; de gra&ccedil;a e seus terceiros licenciantes reservam-se todos os direitos n&atilde;o expressamente licenciados de acordo com este Contrato. O Usu&aacute;rio declara e reconhece que o download de qualquer conte&uacute;do do Site n&atilde;o lhe confere a propriedade sobre quaisquer marcas exibidas no Site.</p>
<p>6.4 Quaisquer marcas exibidas no Site ou qualquer outro site operado em conjunto com o &Eacute; de gra&ccedil;a n&atilde;o devem ser consideradas como de dom&iacute;nio p&uacute;blico e s&atilde;o de propriedade exclusiva do &Eacute; de gra&ccedil;a ou de seus terceiros licenciantes.</p>
<p>&nbsp;</p>
<p>7 VIOLA&Ccedil;&Atilde;O NO SISTEMA OU BASE DE DADOS.</p>
<p>7.1 N&atilde;o &eacute; permitida a utiliza&ccedil;&atilde;o de nenhum dispositivo, software, ou outro recurso que venha a interferir nas atividades e opera&ccedil;&otilde;es do &Eacute; de gra&ccedil;a, bem como nas publica&ccedil;&otilde;es de Oferta, descri&ccedil;&otilde;es, contas ou seus bancos de dados. Qualquer intromiss&atilde;o, tentativa de, ou atividade que viole ou contrarie as leis de direito de propriedade intelectual e/ou as proibi&ccedil;&otilde;es estipuladas neste Termo de Uso, tornar&atilde;o o respons&aacute;vel pass&iacute;vel das a&ccedil;&otilde;es legais pertinentes, bem como das san&ccedil;&otilde;es aqui previstas, sendo ainda respons&aacute;vel pelas indeniza&ccedil;&otilde;es por eventuais danos causados.</p>
<p>&nbsp;</p>
<p>8. SAN&Ccedil;&Otilde;ES.</p>
<p>8.1 Sem preju&iacute;zo de outras medidas, o &Eacute; de gra&ccedil;a poder&aacute; advertir, suspender ou cancelar, tempor&aacute;ria ou definitivamente, a conta de um Usu&aacute;rio a qualquer tempo, e iniciar as a&ccedil;&otilde;es legais cab&iacute;veis se: a) o Usu&aacute;rio n&atilde;o cumprir qualquer dispositivo deste Termo de Uso; b) se descumprir com seus deveres de Usu&aacute;rio; c) se praticar atos fraudulentos ou dolosos; d) se n&atilde;o puder ser verificada a identidade do Usu&aacute;rio ou qualquer informa&ccedil;&atilde;o fornecida por ele esteja incorreta; e) se o &Eacute; de gra&ccedil;a entender que os an&uacute;ncios ou qualquer atitude do Usu&aacute;rio tenham causado algum dano a terceiros ou ao pr&oacute;prio &Eacute; de gra&ccedil;a ou tenham a potencialidade de assim o fazer. Nos casos de inabilita&ccedil;&atilde;o do cadastro do Usu&aacute;rio, todas as Aquisi&ccedil;&otilde;es de Ofertas ativas ser&atilde;o automaticamente canceladas. O &Eacute; de gra&ccedil;a reserva-se o direito de, a qualquer momento e a seu exclusivo crit&eacute;rio, solicitar o envio de documenta&ccedil;&atilde;o pessoal.</p>
<p>&nbsp;</p>
<p>9. DISPOSI&Ccedil;&Otilde;ES GERAIS</p>
<p>9.1 Estes Termos de Uso n&atilde;o gera nenhum contrato de sociedade, franquia ou rela&ccedil;&atilde;o de trabalho entre a &Eacute; de gra&ccedil;a e o Usu&aacute;rio. O Usu&aacute;rio manifesta ci&ecirc;ncia de que o &Eacute; de gra&ccedil;a n&atilde;o &eacute; parte de nenhuma transa&ccedil;&atilde;o, nem possui controle algum sobre a qualidade e a seguran&ccedil;a dos produtos e/ou servi&ccedil;os anunciados. O &Eacute; de gra&ccedil;a n&atilde;o se responsabiliza por qualquer dano, preju&iacute;zo ou perda no equipamento do Usu&aacute;rio causado por falhas no sistema, no servidor ou na internet decorrentes de condutas de terceiros.</p>
<p>9.2 O &Eacute; de gra&ccedil;a tamb&eacute;m n&atilde;o ser&aacute; respons&aacute;vel por qualquer v&iacute;rus que possa atacar o equipamento do Usu&aacute;rio em decorr&ecirc;ncia do acesso, utiliza&ccedil;&atilde;o ou navega&ccedil;&atilde;o no site na internet; ou como conseq&uuml;&ecirc;ncia da transfer&ecirc;ncia de dados, arquivos, imagens, textos ou &aacute;udio. Eventualmente, o sistema poder&aacute; n&atilde;o estar dispon&iacute;vel por motivos t&eacute;cnicos ou falhas da internet, ou por qualquer outro evento fortuito ou de for&ccedil;a maior alheio ao controle do&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &Eacute; de gra&ccedil;a. Em decorr&ecirc;ncia disso, o Usu&aacute;rio n&atilde;o poder&aacute; atribuir ao &Eacute; de gra&ccedil.a qualquer responsabilidade nem exigir indeniza&ccedil;&atilde;o em virtude de preju&iacute;zos resultantes de dificuldades t&eacute;cnicas ou falhas nos sistemas ou na internet.</p>
<p>9.3 O website pode referenciar outros sites da rede, mediante a apresenta&ccedil;&atilde;o de links, o que n&atilde;o significa que esses sites sejam de propriedade ou operados pelo &Eacute; de gra&ccedil;a. O &Eacute; de gra&ccedil;a n&atilde;o ser&aacute; respons&aacute;vel pelos conte&uacute;dos, pr&aacute;ticas e servi&ccedil;os ofertados em referidos websites. A presen&ccedil;a de links para outros sites n&atilde;o implica rela&ccedil;&atilde;o de sociedade, de supervis&atilde;o, de cumplicidade ou solidariedade do &Eacute; de gra&ccedil;a para com esses sites e seus conte&uacute;dos.</p>
<p>9.4 O Usu&aacute;rio indenizar&aacute; o &Eacute; de gra&ccedil;a, suas filiais, empresas controladas ou controladoras, diretores, administradores, colaboradores, representantes e empregados por qualquer demanda promovida por outros usu&aacute;rios ou terceiros decorrentes de suas atividades no site ou por seu descumprimento dos Termos de Uso ou pela viola&ccedil;&atilde;o de qualquer lei ou direitos de terceiros, incluindo honor&aacute;rios de advogados.</p>
<p>9.5 O &Eacute; de gra&ccedil;a poder&aacute; alterar, a qualquer tempo, este Termo de Uso, visando seu aprimoramento e melhoria dos servi&ccedil;os prestados. O novo Termo de Uso entrar&aacute; em vigor a partir de sua publica&ccedil;&atilde;o no website. No prazo de 24 (vinte e quatro) horas contadas a partir da publica&ccedil;&atilde;o das modifica&ccedil;&otilde;es, o Usu&aacute;rio dever&aacute; comunicar-se por e-mail, caso n&atilde;o concorde com o Termo de Uso alterado. Nesse caso, o v&iacute;nculo contratual deixar&aacute; de existir, desde que n&atilde;o haja contas ou d&iacute;vidas em aberto em nome do Usu&aacute;rio. N&atilde;o havendo manifesta&ccedil;&atilde;o no prazo estipulado, entender-se-&aacute; que o Usu&aacute;rio aceitou tacitamente o novo Termo de Uso e o contrato continuar&aacute; vinculando as partes.</p>
<p>&nbsp;</p>
<p>10. FORO</p>
<p>As partes elegem o Foro da Cidade do Recife para dirimir quaisquer conflitos relacionados a estes Termos de Uso.</p>
<p>&nbsp;</p>

    </div>
    
    
    
    
    
</div> <!-- fim div main-left-->

<?php /*include('inc/direita-promocoes.php'); */?>
</div><!-- fim div main-->
<?php include('inc/footer.php'); ?> 



</body>
</html>